### ISSUE TITLE
Linux install fails

### ISSUE THREAD

**Issue by apascualgarcia** [tylermorganwall/rayvertex#13]
Hi there,  I am unable to install the package in Linux (R3.6):

> > install.packages("rayvertex")
> Installing package into ‘/home/apascual/R/x86_64-pc-linux-gnu-library/3.6’
> (as ‘lib’ is unspecified)
> probando la URL 'http://stat.ethz.ch/CRAN/src/contrib/rayvertex_0.4.11.tar.gz'
> Content type 'application/x-gzip' length 468801 bytes (457 KB)
> ==================================================
> downloaded 457 KB
> 
> 
> *** Successfully loaded .Rprofile ***
> 
> * installing *source* package ‘rayvertex’ ...
> ** package ‘rayvertex’ successfully unpacked and MD5 sums checked
> ** using staged installation
> ** libs
> g++ -std=gnu++17 -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG  -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/spacefillr/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/RcppThread/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/rayimage/include" -I/usr/local/include -I../src/glm -I../src/glm/gtc -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
> g++ -std=gnu++17 -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG  -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/spacefillr/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/RcppThread/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/rayimage/include" -I/usr/local/include -I../src/glm -I../src/glm/gtc -fpic  -g -O2  -c filltri.cpp -o filltri.o
> g++ -std=gnu++17 -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG  -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/spacefillr/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/RcppThread/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/rayimage/include" -I/usr/local/include -I../src/glm -I../src/glm/gtc -fpic  -g -O2  -c light.cpp -o light.o
> g++ -std=gnu++17 -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG  -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/spacefillr/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/RcppThread/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/rayimage/include" -I/usr/local/include -I../src/glm -I../src/glm/gtc -fpic  -g -O2  -c line.cpp -o line.o
> g++ -std=gnu++17 -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG  -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/spacefillr/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/RcppThread/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/rayimage/include" -I/usr/local/include -I../src/glm -I../src/glm/gtc -fpic  -g -O2  -c load_obj.cpp -o load_obj.o
> g++ -std=gnu++17 -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG  -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/spacefillr/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/RcppThread/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/rayimage/include" -I/usr/local/include -I../src/glm -I../src/glm/gtc -fpic  -g -O2  -c load_ply.cpp -o load_ply.o
> g++ -std=gnu++17 -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG  -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/spacefillr/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/RcppThread/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/rayimage/include" -I/usr/local/include -I../src/glm -I../src/glm/gtc -fpic  -g -O2  -c miniply.cpp -o miniply.o
> g++ -std=gnu++17 -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG  -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/spacefillr/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/RcppThread/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/rayimage/include" -I/usr/local/include -I../src/glm -I../src/glm/gtc -fpic  -g -O2  -c rasterize_lines_rcpp.cpp -o rasterize_lines_rcpp.o
> g++ -std=gnu++17 -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG  -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/spacefillr/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/RcppThread/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/rayimage/include" -I/usr/local/include -I../src/glm -I../src/glm/gtc -fpic  -g -O2  -c rayimage.cpp -o rayimage.o
> g++ -std=gnu++17 -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG  -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/spacefillr/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/RcppThread/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/rayimage/include" -I/usr/local/include -I../src/glm -I../src/glm/gtc -fpic  -g -O2  -c rayraster.cpp -o rayraster.o
> g++ -std=gnu++17 -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG  -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/spacefillr/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/RcppThread/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/rayimage/include" -I/usr/local/include -I../src/glm -I../src/glm/gtc -fpic  -g -O2  -c shaders.cpp -o shaders.o
> g++ -std=gnu++17 -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG  -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/spacefillr/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/RcppThread/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/rayimage/include" -I/usr/local/include -I../src/glm -I../src/glm/gtc -fpic  -g -O2  -c tonemap.cpp -o tonemap.o
> g++ -std=gnu++17 -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG  -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/spacefillr/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/RcppThread/include" -I"/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/rayimage/include" -I/usr/local/include -I../src/glm -I../src/glm/gtc -fpic  -g -O2  -c wireframe.cpp -o wireframe.o
> g++ -std=gnu++17 -shared -L/opt/R/3.6.3/lib/R/lib -L/usr/local/lib -o rayvertex.so RcppExports.o filltri.o light.o line.o load_obj.o load_ply.o miniply.o rasterize_lines_rcpp.o rayimage.o rayraster.o shaders.o tonemap.o wireframe.o -L/opt/R/3.6.3/lib/R/lib -lR
> installing to /home/apascual/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-rayvertex/00new/rayvertex/libs
> ** R
> Error in parse(outFile) : 
>   /tmp/Rtmpb2IhYf/R.INSTALL18d55fa23fa0/rayvertex/R/add_shape.R:795:30: unexpected '>'
> 794:     scaleval = (bbox_size + material$toon_outline_width)/bbox_size
> 795:     single_obj = single_obj |>
>                                   ^
> ERROR: unable to collate and parse R files for package ‘rayvertex’

I've seen a similar problem [here](https://stackoverflow.com/questions/38139808/r-encoding-issues-when-installing-package-from-github) that seems to be related with an encoding problem.

Thanks in advance

**Comment by trevorld** [comment]
```r
Error in parse(outFile) :
/tmp/Rtmpb2IhYf/R.INSTALL18d55fa23fa0/rayvertex/R/add_shape.R:795:30: unexpected '>'
794: scaleval = (bbox_size + material$toon_outline_width)/bbox_size
795: single_obj = single_obj |>
```

* Looks like the new R pipe `|>` might be used in `add_shape.R`.  The new R pipe `|>` was introduced with R v4.1 and does not work with earlier R versions.  
* Judging from your target library directory `/home/apascual/R/x86_64-pc-linux-gnu-library/3.6/` it looks like you have R v3.6.

**Comment by apascualgarcia** [comment]
Yes, I am using R v3.6. Perhaps documenting that R v4.1 is needed? FYI, I was trying to install your package because `rayshader` requires it, so I guess the authors should also document this limitation.

Thanks for your help

**Comment by trevorld** [comment]
I'm not sure how the maintainer @tylermorganwall wants to handle this issue going forward but in the meantime CRAN maintains an archive of earlier `{rayvertex}` releases some of which may work for you: https://cran.r-project.org/src/contrib/Archive/rayvertex/ .  You could try downloading one of them and installing it e.g. via `R CMD INSTALL`.  Or if you know a desired older git commit hash or tag you can use `remotes::install_github("tylermorganwall/rayvertex", ref = "commithash")` or `remotes::install_github("tylermorganwall/rayvertex", ref = "committag")` to install an older version of the package from the github repo.

**Comment by tylermorganwall** [comment]
I updated the requirements to include R 4.1.0 at a minimum (on the github repo), so you should at least get a more informative error when trying to install the package.
