### ISSUE TITLE
Can't seem to install rayvertex, I get the following:

### ISSUE THREAD

**Issue by NeilKaye** [tylermorganwall/rayvertex#4]
install.packages("rayvertex")
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘rayvertex’
  These will not be installed

**Comment by tylermorganwall** [comment]
Either wait a few days for CRAN to build the package binaries, or install RTools (if you're on windows) to compile the package yourself:

https://cran.r-project.org/bin/windows/Rtools/
