### ISSUE TITLE
Bump {rayimage} version requirement in DESCRIPTION?

### ISSUE THREAD

**Issue by trevorld** [tylermorganwall/rayvertex#7]
1) I tried updating my version of {rayvertex} to 0.3.3 and I initially got the following error:

```
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include' -I'/usr/local/lib/R/site-library/spacefillr/include' -I'/usr/local/lib/R/site-library/RcppThread/include' -I'/usr/local/lib/R/site-library/rayimage/include'   -I../src/glm -I../src/glm/gtc -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c rayraster.cpp -o rayraster.o
rayraster.cpp:20:10: fatal error: stb_image_resize.h: No such file or directory
   20 | #include "stb_image_resize.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

2) I then installed the system package ``libstb-dev`` then tried updating {rayvertex} again and still observed the same error.
3) I then updated {rayimage} and then tried updating {rayvertex} again and it worked.

So maybe the newer version of {rayvertex} requires a newer version of {rayimage}?

**Comment by tylermorganwall** [comment]
Thanks for pointing it out—I'll update it in the next version.

**Comment by trevorld** [comment]
Bumped in aa8c52e0ab1676555b3208e5f81758bce9c05859
